######################################################################
# Automatically generated by qmake (2.00a) Mon 22. May 11:43:21 2006
######################################################################

TEMPLATE = vcapp
TARGET += 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DecompilerThread.h mainwindow.h
FORMS += boomerang.ui
SOURCES += DecompilerThread.cpp main.cpp mainwindow.cpp
