//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by boomerang.rc
//
#define IDC_MYICON                      2
#define IDC_ADDBUTTON                   3
#define IDC_REMOVEBUTTON                4
#define IDC_CLEARBUTTON                 5
#define IDI_PROC                        5
#define IDD_BOOMERANG_DIALOG            102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_BOOMERANG                   107
#define IDC_BOOMERANG                   109
#define IDR_MAINFRAME                   128
#define IDD_NEWPROJECT                  129
#define IDD_DEBUGOPTIONS                130
#define IDD_DECOMPILEOPTIONS            131
#define IDD_DECODEOPTIONS               132
#define IDD_DECODING                    133
#define IDD_PROCPROPERTIES              136
#define IDD_LPROCPROPERTIES             137
#define IDI_CLUSTER                     138
#define IDI_DPROC                       140
#define IDI_ULPROC                      141
#define IDI_LPROC                       142
#define IDI_RESUME                      143
#define IDI_SUSPEND                     144
#define IDI_RESUME1                     145
#define IDD_SYMBOLTABLE                 145
#define IDD_MEMORYDUMP                  146
#define IDC_NAME                        1000
#define IDC_TARGET                      1001
#define IDC_BROWSEBUTTON                1002
#define IDC_OUTPUT                      1003
#define IDC_BROWSEBUTTON2               1004
#define IDC_CHECKDECODEINDIRECT         1005
#define IDC_CHECKSA                     1006
#define IDC_CHECKD                      1007
#define IDC_CHECKCG                     1008
#define IDC_CHECKL                      1009
#define IDC_CHECKPROOF                  1010
#define IDC_CHECKUR                     1011
#define IDC_CHECKTA                     1012
#define IDC_CHECKUS                     1013
#define IDC_RADIOMAIN                   1018
#define IDC_RADIOSTART                  1019
#define IDC_RADIONEITHER                1020
#define IDC_COMBOENTRYPOINT             1022
#define IDC_LISTENTRYPOINT              1023
#define IDC_CHECKDECODECHILDREN         1024
#define IDC_COMBOSYMBOLFILE             1027
#define IDC_BROWSEBUTTON3               1028
#define IDC_CHECKNOSIMPBRANCHES         1029
#define IDC_CHECKRTL                    1030
#define IDC_CHECKNOREMOVENULL           1030
#define IDC_CHECKTD                     1031
#define IDC_CHECKNOCREATELOCAL          1031
#define IDC_DECOMPILEOPTIONS            1032
#define IDC_CHECKNOPARAMS               1032
#define IDC_DEBUGOPTIONS                1033
#define IDC_DECODEOPTIONS               1034
#define IDC_CHECKNOUNNEEDEDLABELS       1034
#define IDC_CHECKAST                    1035
#define IDC_CHECKNOUNNEEDEDRETURNS      1035
#define IDC_CHECKV                      1036
#define IDC_CHECKNODATAFLOW             1036
#define IDC_CHECKNODECOMP               1037
#define IDC_CHECKNOPROOF                1038
#define IDC_CHECKNOCHANGESIGS           1039
#define IDC_LOCALS                      1041
#define IDC_SIGNATURE_RETURNS           1042
#define IDC_SIGNATURE_PARAMS            1043
#define IDC_SIGNATURE_NAME              1044
#define IDC_REREADSIGS                  1045
#define IDC_MSDN                        1046
#define IDC_LIST1                       1047
#define IDC_SCROLLBAR1                  1048
#define IDC_RADIOCTA                    1050
#define IDC_RADIODFTA                   1051
#define IDC_RADIONTA                    1052
#define ID_FILE_NEW                     32771
#define ID_FILE_OPEN                    32773
#define ID_FILE_CLOSE                   32775
#define ID_FILE_RECENTPROJECTS          32776
#define ID_NEW_PROJECT                  32777
#define ID_OPEN_PROJECT                 32778
#define ID_FILE_SAVE                    32779
#define ID_HELP_BOOMERANGWEBSITE        32780
#define ID_HELP_BOOMERANGFAQ            32781
#define ID_TOOLS_DECOMPILER             32782
#define ID_DECOMPILER_RESUME            32784
#define ID_DECOMPILER_TERMINATE         32785
#define ID_DECOMPILER_SUSPEND           32786
#define ID_EDIT_COPY                    32787
#define ID_EDIT_PASTE                   32788
#define ID_EDIT_UNDO                    32789
#define ID_EDIT_REDO                    32790
#define ID_EDIT_SELECTALL               32791
#define ID_VIEW_CODE                    32792
#define ID_VIEW_RTL                     32793
#define ID_TOOLS_DECODER                32795
#define ID_DECODER_SHOWCOVERAGE         32796
#define ID_TOOLS_CODEGENERATOR          32797
#define ID_DECODER_NEWADDRESS           32798
#define ID_TOOLS_CODEGENERATOR32800     32800
#define ID_CODEGENERATOR_REGENERATEALL  32801
#define ID_SETOUTPUTPATH                32802
#define ID_DECOMPILER_OPTIONS           32803
#define ID_DECODER_OPTIONS              32804
#define ID_VIEW_MIXED                   32805
#define ID_DECOMPILER_START             32806
#define ID_VIEW_PROPERTIES              32807
#define ID_VIEW_GLOBALS                 32808
#define ID_VIEW_NEWCLUSTER              32809
#define ID_VIEW_DELETECLUSTER           32810
#define ID_VIEW_RENAME                  32814
#define ID_TO_SSA                       32815
#define ID_TOOLS_LOADER                 32815
#define ID_PROP_REGS                    32816
#define ID_FROM_SSA                     32817
#define ID_LOADER_MEMORYDUMP            32818
#define ID_STMT_PROPAGATE_TO            32819
#define ID_LOADER_SYMBOLTABLE           32820
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32818
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
