#define YY_CHAR char
#line 1 "//usr/local/lib/flexskel.cc"
/* A lexical scanner generated by flex */
/* scanner skeleton version:
 * $Header$
 */
/* MODIFIED FOR C++ CLASS BY Alain Coetmeur: coetmeur(at)icdc.fr */
/* Note that (at) mean the 'at' symbol that I cannot write */
/* because it is expanded to the class name */
/* made at Informatique-CDC, Research&development department */
/* company from the Caisse Des Depots et Consignations */
/* institutional financial group  */

/* theses symbols are added before this file */
/* #define YY_CHAR 'unsigned char' if 8bit or 'char' if 7bit */
/* #define FLEX_DEBUG if debug mode */
#define FLEX_SCANNER
/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif
/* Old MSC, before c7 */
#ifdef MSDOS
#ifndef _MSDOS
#define _MSDOS
#endif
#endif
/* turboc */
#ifdef __MSDOS__
#ifndef _MSDOS
#define _MSDOS
#endif
#endif

#ifdef __cplusplus
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#ifndef YY_USE_CLASS
#define YY_USE_CLASS
#endif
#ifndef _MSDOS
#include <osfcn.h>
#endif
#else   /* ! __cplusplus */
#ifdef __STDC__
#ifdef __GNUC__
#include <stddef.h>
void *malloc( size_t );
void free( void* );
int read();
#else
#include <stdlib.h>
#endif  /* __GNUC__ */
#define YY_USE_PROTOS
#define YY_USE_CONST
#endif  /* __STDC__ */
#endif  /* ! __cplusplus */
#ifdef __TURBOC__
#define YY_USE_CONST
#endif
#include <stdio.h>


/*********************************************/
/* COMPILER DEPENDENT   MACROS               */
/*********************************************/
/* use prototypes in function declarations */
/* the "const" storage-class-modifier is valid */
#ifndef YY_USE_CONST
#define const
#endif
/* use prototypes in function declarations */
#ifndef YY_PROTO
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
#endif


/*********************/
/* parameters        */

/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif
/* size of default input buffer */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) 
#endif

/***********************************/
/* to be redefined for application */

/* returned upon end-of-file */
#define YY_END_TOK 0
/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* code executed at the end of each rule */
#define YY_BREAK break;

/* #define YY_USER_ACTION */
/* #define YY_USER_INIT */


#ifndef YY_USE_CLASS
/* copy whatever the last rule matched to the standard output */
/* cast to (char *) is because for 8-bit chars, yy___text is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yy___text, yy___leng, 1, yy___out )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifdef _MSDOS
#define YY_INPUT(buf,result,max_size) \
	if ( (result = fread(buf,1,max_size,yy___in)) < 0 ) \
	    YY_FATAL_ERROR( "fread() in flex scanner failed" );
#else
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yy___in), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );

#endif
/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 *      if ( something_happens )
 *              YY_FATAL_ERROR( "oops, the something happened" );
 *      else
 *              everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) fputs( msg, yy___stderr  ); \
		(void) putc( '\n', yy___stderr  ); \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1


/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void )) 
#else 
/* c++ */
#define ECHO yy___echo()
#define YY_INPUT(buf,result,max_size) \
	if ( yy___input((char *)buf, result,max_size) < 0 ) \
	    YY_FATAL_ERROR( "YY_INPUT() in flex scanner failed" );

#define YY_FATAL_ERROR(msg) yy___fatal_error(msg)
#define yywrap() yy___wrap()

#endif
/***********************************/
/* not to be changed */
#define YY_NULL 0
#define YY_END_OF_BUFFER_CHAR 0
/* special action meaning "start processing a new file" */
#define YY_NEW_FILE yy___newfile 
/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)



/* % section 1 definitions go here */ 
#line 1 "sslscanner.l"
#define INITIAL 0
/*
 * Copyright (C) 1997, Shane Sendall
 * Copyright (C) 1998-2001, The University of Queensland
 * Copyright (C) 2001, Sun Microsystems, Inc
 *
 * See the file "LICENSE.TERMS" for information on usage and
 * redistribution of this file, and for a DISCLAIMER OF ALL
 * WARRANTIES.
 *
 */
/*==============================================================================
 * FILE:          sslscanner.l
 * OVERVIEW:      Defines a scanner to parse the tokens of a Semantic
 *                Specification Language specification.
 *============================================================================*/
/* 
 * Shane Sendall (original C version) Dec 1997
 * Doug Simon (C++ version) Jan 1998
 * 29 Apr 02 - Mike: Mods for boomerang; removed &~, |~, and ^~ operators
 * 09 May 02 - Mike: ASSIGNSIZE is an num now
 */
#define YY_SSLScanner_FLEX_SCANNER
#line 34 "sslscanner.l"
#include <assert.h>
#if defined(_MSC_VER) && _MSC_VER <= 1200
#pragma warning(disable:4786)
#endif 

#include "sslscanner.h"
#include "sslscanner.h"
#line 61 "sslscanner.l"
#line 196 "//usr/local/lib/flexskel.cc"

#define yy___stderr YY_SSLScanner_ERRFILE
#define yy___text YY_SSLScanner_TEXT
#define yy___leng YY_SSLScanner_LENG
#define yy___in YY_SSLScanner_IN
#define yy___out YY_SSLScanner_OUT
#define yy___newfile \
	do \
		{ \
		YY_SSLScanner_INIT_BUFFER( YY_SSLScanner_CURRENT_BUFFER, yy___in ); \
		YY_SSLScanner_LOAD_BUFFER_STATE(); \
		} \
	while ( 0 )
#if YY_SSLScanner_DEBUG != 0
#define yy___flex_debug YY_SSLScanner_DEBUG_FLAG
#endif


#ifdef YY_USE_CLASS

#define yy___echo YY_SSLScanner_ECHO
#define yy___input YY_SSLScanner_INPUT
#define yy___fatal_error YY_SSLScanner_FATAL_ERROR
#define yy___wrap YY_SSLScanner_WRAP

#endif

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yy___text
 */
#define YY_DO_BEFORE_ACTION \
	yy___text = yy_bp; \
/* % code to fiddle yy___text and yy___leng for yymore() goes here */ \
	yy___leng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yy___text */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yy___text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yy___text )



struct yy_buffer_state
    {
    YY_SSLScanner_IFILE  *yy_input_file;

    YY_SSLScanner_CHAR *yy_ch_buf;               /* input buffer */
    YY_SSLScanner_CHAR *yy_buf_pos;      /* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters */
    int yy_buf_size;    

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;          /* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */

#ifndef YY_USE_CLASS

#if YY_SSLScanner_DEBUG != 0
int YY_SSLScanner_DEBUG_FLAG=YY_SSLScanner_DEBUG_INIT;
#endif
#define YY_CURRENT_BUFFER YY_SSLScanner_CURRENT_BUFFER
static YY_BUFFER_STATE YY_SSLScanner_CURRENT_BUFFER;
/* yy_hold_char holds the character lost when yy___text is formed */
static YY_SSLScanner_CHAR yy_hold_char;

static int yy_n_chars;          /* number of characters read into yy_ch_buf */

/* GLOBAL */
YY_SSLScanner_CHAR *yy___text;
int yy___leng;

YY_SSLScanner_IFILE  *yy___in = (YY_SSLScanner_IFILE  *) 0;
YY_SSLScanner_OFILE *yy___out = (YY_SSLScanner_OFILE  *) 0;

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_SSLScanner_CHAR *yy_c_buf_p = (YY_SSLScanner_CHAR *) 0;
static int yy_init = 1;         /* whether we need to initialize */
static int yy_start = 0;        /* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yy___in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_SSLScanner_CHAR c, YY_SSLScanner_CHAR *buf_ptr ));

#else
/* c++ */
#ifndef YY_SSLScanner_ECHO_NOCODE
void YY_SSLScanner_CLASS::yy___echo()
{YY_SSLScanner_ECHO_CODE
}
#endif
#ifndef YY_SSLScanner_INPUT_NOCODE
int  YY_SSLScanner_CLASS::yy___input(char * buffer,int &result,int max_size)
{YY_SSLScanner_INPUT_CODE
}
#endif
#ifndef YY_SSLScanner_FATAL_ERROR_NOCODE
void YY_SSLScanner_CLASS::yy___fatal_error(char *msg)
{YY_SSLScanner_FATAL_ERROR_CODE
}
#endif
#ifndef YY_SSLScanner_WRAP_NOCODE
int  YY_SSLScanner_CLASS::yy___wrap()
{YY_SSLScanner_WRAP_CODE
}
#endif
void YY_SSLScanner_CLASS::yy_initialize()
{
 yy___in=0;yy___out=0;yy_init = 1;
 yy_start=0;
 yy___text=0;yy___leng=0;
 YY_SSLScanner_CURRENT_BUFFER=0;
 yy_did_buffer_switch_on_eof=0;
 yy_c_buf_p=0;yy_hold_char=0;yy_n_chars=0;
#if YY_SSLScanner_DEBUG != 0
 YY_SSLScanner_DEBUG_FLAG=YY_SSLScanner_DEBUG_INIT;
#endif
}

YY_SSLScanner_CLASS::YY_SSLScanner_CLASS(YY_SSLScanner_CONSTRUCTOR_PARAM) YY_SSLScanner_CONSTRUCTOR_INIT
{yy_initialize();
 YY_SSLScanner_CONSTRUCTOR_CODE;
}
YY_SSLScanner_CLASS::~YY_SSLScanner_CLASS() 
{YY_SSLScanner_DESTRUCTOR_CODE;
 if(YY_SSLScanner_CURRENT_BUFFER)
  YY_SSLScanner_DELETE_BUFFER(YY_SSLScanner_CURRENT_BUFFER);
}

#endif


#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

/* % data tables for the DFA go here */ 
#define YY_END_OF_BUFFER 119
typedef int yy_state_type;
static const short int yy_acclist[467] =
    {   0,
      119,  116,  118,  114,  116,  118,  117,  118,   69,  116,
      118,  105,  116,  118,  116,  118,16499,  109,  116,  118,
       39,  116,  118,   37,  116,  118,   40,  116,  118,   45,
      116,  118,   46,  116,  118,  116,  118,   41,  116,  118,
      111,  116,  118,  111,  116,  118,  111,  116,  118,   68,
      116,  118,  108,  116,  118,   21,  116,  118,   19,  116,
      118,   22,  116,  118,   70,  116,  118,  102,  116,  118,
      102,  116,  118,  102,  116,  118,  102,  116,  118,  102,
      116,  118,  102,  116,  118,  102,  116,  118,  102,  116,
      118,  102,  116,  118,  107,  116,  118,  106,  116,  118,

       38,  116,  118,   98,  116,  118,  102,  116,  118,  102,
      116,  118,  102,  116,  118,  102,  116,  118,  102,  116,
      118,  102,  116,  118,  102,  116,  118,  102,  116,  118,
      102,  116,  118,  102,  116,  118,  102,  116,  118,   96,
      102,  116,  118,  102,  116,  118,  102,  116,  118,  102,
      116,  118,  102,  116,  118,   36,  116,  118,   62,  116,
      118,  114,  117,16499, 8307,   44,   99,   42,   47,   55,
      111,  111,   64,   58,   67,  103,   43,   52,   65,   34,
       23,   25,   63,   24,   33,   26,  100,  102,  101,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,

      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,   97,  101,   17,
      102,  102,   96,  102,   95,  101,   31,  102,   32,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,   20,
       99,   16,   48,   49,   56,   57,   59,   60,  103,   53,
       54,  110,  112,   66,   27,   28,   35,    8,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,   18,  102,  102,    9,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,   61,  102,
       29,  102,   30,  102,  102,  102,  102,  102,  102,   94,

      102,  102,  102,  102,   51,   50,  113,  102,  102,   14,
      102,  102,  102,   82,  102,  102,  102,  102,  102,  102,
      104,  102,  102,   85,  100,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,   84,
      100,  102,  102,   86,  100,   94,  102,  102,  102,  102,
      102,  102,  102,    3,  102,   83,  102,  102,  102,  102,
      102,   71,  100,  102,  102,  102,  102,    4,  102,  102,
      102,   74,  100,  102,   73,  100,  102,  102,   88,  100,
       89,  100,  102,   92,  100,   93,  100,  102,  102,  102,
       12,  102,  102,  102,  102,   10,  102,  102,   13,  102,

      102,  102,  102,  102,  102,   72,  100,  102,   11,  102,
       90,  100,   79,  100,  102,  102,  102,   78,  100,  102,
      102,    1,  102,    5,  102,   87,  100,  102,  102,  102,
       75,  100,    2,  102,   77,  100,   76,  100,  102,  102,
      102,  102,  102,   91,  100,  102,  102,   15,  102,  102,
      102,  102,    6,  102,  102,    7,  102,  102,  102,  102,
       80,  100,  102,  102,   81,  100
    } ;

static const short int yy_accept[325] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   15,   18,
       21,   24,   27,   30,   33,   36,   38,   41,   44,   47,
       50,   53,   56,   59,   62,   65,   68,   71,   74,   77,
       80,   83,   86,   89,   92,   95,   98,  101,  104,  107,
      110,  113,  116,  119,  122,  125,  128,  131,  134,  137,
      140,  144,  147,  150,  153,  156,  159,  162,  163,  164,
      165,  166,  167,  168,  169,  169,  170,  171,  172,  173,
      174,  175,  176,  177,  178,  179,  179,  179,  179,  179,
      180,  181,  182,  183,  184,  185,  186,  187,  188,  189,
      190,  191,  192,  193,  194,  195,  196,  197,  198,  199,

      200,  201,  201,  202,  203,  204,  205,  206,  207,  208,
      209,  210,  211,  212,  213,  214,  215,  216,  217,  218,
      220,  222,  223,  225,  227,  229,  231,  232,  233,  234,
      235,  236,  237,  238,  239,  240,  241,  242,  243,  244,
      245,  245,  246,  247,  248,  249,  250,  251,  252,  253,
      254,  254,  255,  256,  257,  258,  260,  261,  262,  263,
      264,  265,  266,  267,  268,  269,  270,  271,  271,  272,
      274,  275,  277,  278,  279,  280,  281,  282,  283,  284,
      285,  286,  287,  288,  289,  291,  293,  295,  296,  297,
      298,  299,  300,  302,  303,  304,  305,  306,  307,  308,

      309,  310,  312,  313,  314,  316,  317,  318,  319,  320,
      321,  322,  322,  323,  324,  326,  327,  328,  329,  330,
      331,  332,  333,  334,  335,  336,  337,  338,  339,  340,
      342,  343,  344,  346,  348,  349,  350,  351,  352,  353,
      354,  356,  358,  359,  360,  361,  362,  364,  365,  366,
      367,  368,  370,  371,  372,  374,  375,  377,  378,  379,
      381,  383,  384,  386,  388,  389,  390,  391,  393,  394,
      395,  396,  398,  399,  401,  402,  403,  404,  405,  406,
      408,  409,  411,  413,  415,  416,  417,  418,  420,  421,
      422,  424,  426,  428,  429,  430,  431,  433,  435,  437,

      439,  440,  441,  442,  443,  444,  446,  447,  448,  450,
      451,  452,  453,  455,  456,  458,  459,  460,  461,  463,
      464,  465,  467,  467
    } ;

static const YY_CHAR yy_ec[128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       10,   12,   13,   10,   14,   15,   16,   17,   18,   19,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   10,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   36,   37,   36,   38,   39,   40,
       36,   41,   42,   43,   44,   45,   36,   46,   36,   36,
       47,    1,   48,   49,   50,    1,   51,   52,   53,   54,

       55,   56,   57,   36,   58,   36,   36,   59,   60,   61,
       62,   63,   64,   65,   66,   67,   68,   36,   69,   70,
       36,   71,   10,   72,   10,   73,    1
    } ;

static const YY_CHAR yy_meta[74] =
    {   0,
        1,    1,    2,    3,    4,    1,    1,    1,    1,    1,
        5,    1,    1,    1,    6,    1,    7,    7,    7,    7,
        1,    1,    1,    1,    1,    1,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    5,    1,    1,    5,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    1,    1
    } ;

static const short int yy_base[335] =
    {   0,
        0,    0,  211,  931,  203,    0,  931,  931,  201,  931,
      194,  931,   70,  141,   58,  176,   75,   76,   82,   91,
       60,  931,   62,  165,   80,  931,   69,   87,   81,  102,
       96,  104,  106,  107,  110,  931,  931,  184,    0,  108,
      113,  114,  127,  118,  128,  139,  134,  121,  152,  156,
      190,  155,  169,  167,  174,  931,  160,  181,    0,  174,
      931,  931,    0,  931,  221,  161,  168,  227,  239,  931,
      172,  931,    0,  931,  189,  243,  247,  160,  146,  931,
      931,   96,  931,  931,   91,  131,  931,  931,  224,  931,
      237,  241,  257,  258,  269,  262,  271,  270,  278,  261,

      272,    0,  279,  280,  282,  284,  283,  285,  286,  291,
      292,  296,  303,  309,  312,  313,  317,  324,  330,  931,
      335,  337,  375,  931,  343,  350,  338,  341,  342,  351,
      358,  361,  362,  364,  365,  931,    0,  931,   92,  931,
       98,  931,  931,  931,  931,    0,  931,  931,  396,  408,
      414,  931,  931,  931,  931,  370,  410,  409,  399,  418,
      432,  434,  438,  437,  439,  442,  447,  132,  440,  443,
      444,  449,  450,  451,  452,  453,  456,  455,  461,  466,
      465,  481,  467,  507,  482,  484,  493,  504,  505,  506,
      508,  510,  511,  516,  519,  522,  931,  931,  524,  524,

      537,  525,  536,  535,  528,  545,  556,  539,  569,  557,
      931,  130,  538,  576,  931,  579,  582,  583,  587,  584,
      588,  589,  590,  591,  594,  595,  597,  599,  602,  931,
      603,  608,  931,  609,  610,  611,  614,  617,  628,  621,
      613,  637,  651,  654,  658,  660,  931,  659,  663,  665,
      666,  667,  668,  669,  931,  670,  931,  672,  676,  931,
      931,  677,  931,  931,  681,  682,  683,  684,  697,  692,
      710,  689,  723,  698,  721,  726,  730,  731,  732,  931,
      737,  741,  931,  931,  743,  745,  747,  931,  749,  750,
      748,  751,  931,  752,  754,  753,  931,  756,  931,  931,

      758,  765,  793,  763,  772,  931,  774,  776,  778,  782,
      795,  804,  805,  806,  809,  813,  815,  820,  931,  821,
      822,  931,  931,  887,  895,  901,  904,  908,  104,  910,
      913,   74,  918,  922
    } ;

static const short int yy_def[335] =
    {   0,
      323,    1,  323,  323,  323,  324,  323,  323,  325,  323,
      326,  323,  323,  323,  323,  327,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  323,  323,  323,  329,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  323,  323,  323,  324,  325,
      323,  323,  330,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  331,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  328,  323,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  332,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  323,
      328,  328,  328,  323,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  323,  330,  323,  323,  323,
      323,  323,  323,  323,  323,  331,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  333,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  334,  328,  328,  328,  323,  323,  323,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      323,  333,  328,  328,  323,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  323,
      328,  328,  323,  334,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  323,  328,  328,  328,
      328,  328,  328,  328,  323,  328,  323,  328,  328,  323,
      323,  328,  323,  323,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  323,
      328,  328,  323,  323,  328,  328,  328,  323,  328,  328,
      328,  328,  323,  328,  328,  328,  323,  328,  323,  323,

      328,  328,  328,  328,  328,  323,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  323,  328,
      328,  323,    0,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323
    } ;

static const short int yy_nxt[1005] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,    8,
        8,   13,   14,   15,   16,   17,   18,   19,   20,   19,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   27,
       30,   31,   27,   27,   32,   27,   33,   27,   34,   27,
       27,   35,   27,   27,   27,   27,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   27,   46,   47,   48,
       27,   49,   50,   27,   51,   52,   53,   54,   27,   27,
       55,   56,   57,   64,   68,   68,   69,   68,   74,   88,
       79,  168,   70,   80,   81,   82,   65,   65,   65,   65,
       76,   88,   68,   68,   68,   68,   76,   88,   68,   68,

       68,   68,   78,   85,   86,   76,   88,   68,   68,   68,
       68,  103,   88,   71,   88,   90,   88,   88,   88,   92,
       88,   91,   94,   88,   88,   66,   95,   90,   88,   83,
       75,   88,   96,   90,  211,   97,  211,   88,   88,   93,
       99,   98,   90,  101,   88,   77,  100,   87,   90,   88,
       90,  198,   90,   90,   90,  197,   90,  155,  154,   90,
       90,  104,   88,  153,   90,   88,   88,  120,  105,  152,
      107,  151,  106,   90,   90,  108,   61,   88,  110,   88,
       90,  109,   58,  136,   88,   90,  112,  111,  102,   84,
       72,  118,  113,  114,  115,  119,   67,   62,   90,  116,

       88,   90,   90,   61,   58,  117,  123,  123,  123,  123,
      323,  127,  128,   90,  139,   90,  121,  122,  129,  131,
       90,  142,  130,  323,  140,  144,  141,  134,  132,  135,
      323,  143,  138,  133,   88,  145,  124,   65,   65,   65,
       65,   76,  147,   68,   68,   68,   68,   88,  125,  323,
       78,   88,  148,   76,  126,   68,   68,   68,   68,  149,
      149,  149,  149,  150,  150,  150,  150,   88,   88,  156,
       90,   88,   88,  150,  150,  150,  150,  150,  150,   88,
       88,   88,   88,   90,  323,  157,  158,   90,   88,   88,
       88,  166,   88,   88,   88,   88,   88,  323,  167,  159,

      161,   88,   88,   90,   90,  323,   88,   90,   90,  162,
      323,  160,  164,   88,  163,   90,   90,   90,   90,   88,
      165,  323,   88,   88,   90,   90,   90,   88,   90,   90,
       90,   90,   90,  169,   88,  170,  171,   90,   90,  172,
       88,  174,   90,  323,  175,   88,  176,   88,   88,   90,
      173,   88,   88,   88,  323,   90,  323,  177,   90,   90,
       88,   88,  323,   90,  178,  323,  179,  323,   88,  323,
       90,   88,   88,  180,   88,   88,   90,  323,  182,  181,
       88,   90,  323,   90,   90,   88,  184,   90,   90,   90,
      183,  123,  123,  123,  123,  186,   90,   90,  188,  323,

      323,  189,  187,  191,   90,  185,  190,   90,   90,   88,
       90,   90,  149,  149,  149,  149,   90,  195,  192,   88,
       88,   90,  196,  193,  150,  150,  150,  150,   88,  194,
      199,  199,  199,  199,  150,  150,  150,  150,  150,  150,
      200,  202,   88,  201,   88,   90,  203,   88,   88,   88,
       88,  323,   88,   88,   88,   90,   90,   88,  204,   88,
      215,   88,   88,   88,   90,   88,   88,  207,  323,  323,
      323,   88,  323,  205,  323,   88,   88,   88,   90,  206,
       90,  208,  209,   90,   90,   90,   90,  210,   90,   90,
       90,   88,   88,   90,   88,   90,   90,   90,   90,   90,

      323,   90,   90,   88,  213,  218,  219,   90,  216,  217,
      214,   90,   90,   90,   88,  230,   88,   88,   88,  223,
      233,   88,  220,  222,  226,  227,   88,   90,   90,   88,
       90,  221,   88,  225,   88,   88,  224,  323,   88,   90,
      199,  199,  199,  199,  323,   88,   88,   88,  247,   88,
       90,   90,   90,   90,   90,   88,   90,   90,  229,  323,
      232,  228,   90,  239,  238,   90,   88,   88,   90,  240,
       90,   90,  231,  236,   90,  244,  235,  241,  242,   88,
      237,   90,   90,   90,   90,   90,   88,  246,  243,   88,
      323,   90,   88,   88,   88,  245,  323,   88,   88,  255,

       88,  257,   90,   90,   88,   88,  323,  260,  323,  261,
      323,  259,   88,  263,  323,   90,  323,  323,  264,   88,
       88,   88,   90,   88,   88,   90,  248,   88,   90,   90,
       90,   88,  250,   90,   90,   90,   90,   90,   88,  249,
       90,   90,  254,   90,  253,   90,  256,   88,   90,   90,
      251,  270,  258,  252,   90,   90,   90,   90,  268,   90,
       90,   88,  265,   90,   88,  269,  266,   90,   88,   88,
       88,  262,  267,   88,   90,   88,   88,   88,   88,  280,
       88,  271,   88,   90,  272,  323,  283,  284,  323,  323,
      323,   88,   88,  288,   88,  273,  323,   90,  323,   88,

       90,  274,   88,  323,   90,   90,   90,   88,   88,   90,
      323,   90,   90,   90,   90,   90,   90,  276,   90,  275,
       88,  279,   90,   90,  281,  277,  282,   90,   90,   90,
       90,  293,  278,   88,  289,   90,   88,  290,   90,  287,
       88,   88,  297,   90,   90,  323,  285,   88,  286,  323,
      291,   88,  292,  299,  323,  300,   90,   88,   88,   88,
       88,   88,   88,  306,   88,  323,   88,   90,   88,   90,
      323,  323,   90,   88,  323,   88,   90,   90,   90,  302,
      303,  294,   88,   90,   88,  296,   88,   90,   88,   90,
      295,   90,   88,   90,   90,   90,   90,   90,   90,   90,

       90,  298,   90,   88,   90,   88,  308,  301,  305,   90,
      304,   90,  307,  310,   88,   88,   88,  313,   90,   88,
       90,  309,   90,   88,   90,  319,  323,  323,   90,  312,
       88,   88,  322,  323,  323,  323,  323,  311,  314,   90,
      323,   90,  323,  323,  323,  323,  323,  323,  323,  323,
       90,   90,   90,  323,  323,   90,  323,  323,  323,   90,
      315,   90,  316,  318,  323,  323,   90,   90,   90,  323,
      323,  317,  323,  323,  323,  323,  320,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  321,   59,  323,   59,
       59,   59,   59,   59,   59,   60,   60,   60,   60,   60,

       60,   60,   60,   63,  323,  323,  323,  323,   63,   73,
      323,   73,   89,  323,   89,   89,  137,  137,  146,  146,
      146,  212,  323,  323,  323,  212,  234,  323,  234,  234,
        3,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,

      323,  323,  323,  323
    } ;

static const short int yy_chk[1005] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   13,   15,   15,   15,   15,   17,   27,
       21,  332,   15,   21,   23,   23,   13,   13,   13,   13,
       18,   29,   18,   18,   18,   18,   19,   28,   19,   19,

       19,   19,   20,   25,   25,   20,   31,   20,   20,   20,
       20,  329,   30,   15,   32,   27,   33,   34,   40,   29,
       35,   28,   31,   41,   42,   13,   31,   29,   44,   23,
       17,   48,   31,   28,  212,   31,  168,   43,   45,   30,
       33,   32,   31,   35,   47,   18,   34,   25,   30,   46,
       32,  141,   33,   34,   40,  139,   35,   86,   85,   41,
       42,   40,   49,   82,   44,   52,   50,   48,   40,   79,
       41,   78,   40,   43,   45,   42,   60,   54,   44,   53,
       47,   43,   58,   57,   55,   46,   45,   44,   38,   24,
       16,   47,   45,   45,   45,   47,   14,   11,   49,   46,

       51,   52,   50,    9,    5,   46,   51,   51,   51,   51,
        3,   52,   52,   54,   66,   53,   49,   50,   52,   53,
       55,   67,   52,    0,   66,   71,   66,   54,   53,   55,
        0,   67,   65,   53,   89,   71,   51,   65,   65,   65,
       65,   68,   75,   68,   68,   68,   68,   91,   51,    0,
       69,   92,   75,   69,   51,   69,   69,   69,   69,   76,
       76,   76,   76,   77,   77,   77,   77,   93,   94,   91,
       89,  100,   96,   77,   77,   77,   77,   77,   77,   95,
       98,   97,  101,   91,    0,   92,   93,   92,   99,  103,
      104,  100,  105,  107,  106,  108,  109,    0,  101,   94,

       96,  110,  111,   93,   94,    0,  112,  100,   96,   97,
        0,   95,   98,  113,   97,   95,   98,   97,  101,  114,
       99,    0,  115,  116,   99,  103,  104,  117,  105,  107,
      106,  108,  109,  104,  118,  105,  106,  110,  111,  107,
      119,  109,  112,    0,  110,  121,  111,  122,  127,  113,
      108,  128,  129,  125,    0,  114,    0,  112,  115,  116,
      126,  130,    0,  117,  113,    0,  114,    0,  131,    0,
      118,  132,  133,  115,  134,  135,  119,    0,  117,  116,
      156,  121,    0,  122,  127,  123,  119,  128,  129,  125,
      118,  123,  123,  123,  123,  125,  126,  130,  127,    0,

        0,  128,  126,  130,  131,  122,  129,  132,  133,  159,
      134,  135,  149,  149,  149,  149,  156,  134,  131,  158,
      157,  123,  135,  132,  150,  150,  150,  150,  160,  133,
      151,  151,  151,  151,  150,  150,  150,  150,  150,  150,
      157,  159,  161,  158,  162,  159,  160,  164,  163,  165,
      169,    0,  166,  170,  171,  158,  157,  167,  161,  172,
      173,  174,  175,  176,  160,  178,  177,  164,    0,    0,
        0,  179,    0,  162,    0,  181,  180,  183,  161,  163,
      162,  165,  166,  164,  163,  165,  169,  167,  166,  170,
      171,  182,  185,  167,  186,  172,  173,  174,  175,  176,

        0,  178,  177,  187,  169,  176,  177,  179,  174,  175,
      171,  181,  180,  183,  188,  189,  190,  184,  191,  181,
      192,  193,  178,  180,  184,  184,  194,  182,  185,  195,
      186,  179,  196,  183,  200,  202,  182,    0,  205,  187,
      199,  199,  199,  199,    0,  204,  203,  201,  213,  208,
      188,  189,  190,  184,  191,  206,  192,  193,  188,    0,
      191,  184,  194,  201,  200,  195,  207,  210,  196,  203,
      200,  202,  190,  195,  205,  208,  194,  204,  206,  209,
      196,  204,  203,  201,  213,  208,  214,  210,  207,  216,
        0,  206,  217,  218,  220,  209,    0,  219,  221,  222,

      223,  224,  207,  210,  225,  226,    0,  227,    0,  228,
        0,  226,  229,  231,    0,  209,    0,    0,  232,  234,
      235,  236,  214,  241,  237,  216,  214,  238,  217,  218,
      220,  240,  217,  219,  221,  222,  223,  224,  239,  216,
      225,  226,  221,  227,  220,  228,  223,  242,  229,  231,
      218,  240,  225,  219,  232,  234,  235,  236,  238,  241,
      237,  243,  235,  238,  244,  239,  236,  240,  245,  248,
      246,  229,  237,  249,  239,  250,  251,  252,  253,  254,
      256,  243,  258,  242,  244,    0,  259,  262,    0,    0,
        0,  265,  266,  267,  268,  245,    0,  243,    0,  272,

      244,  246,  270,    0,  245,  248,  246,  269,  274,  249,
        0,  250,  251,  252,  253,  254,  256,  249,  258,  248,
      271,  253,  259,  262,  256,  250,  258,  265,  266,  267,
      268,  275,  251,  273,  269,  272,  276,  270,  270,  266,
      277,  278,  279,  269,  274,    0,  265,  281,  265,    0,
      271,  282,  273,  285,    0,  286,  271,  287,  291,  289,
      290,  292,  294,  296,  295,    0,  298,  275,  301,  273,
        0,    0,  276,  304,    0,  302,  277,  278,  279,  289,
      290,  276,  305,  281,  307,  278,  308,  282,  309,  285,
      277,  286,  310,  287,  291,  289,  290,  292,  294,  296,

      295,  281,  298,  303,  301,  311,  302,  287,  295,  304,
      294,  302,  301,  304,  312,  313,  314,  308,  305,  315,
      307,  303,  308,  316,  309,  317,    0,    0,  310,  307,
      318,  320,  321,    0,    0,    0,    0,  305,  310,  303,
        0,  311,    0,    0,    0,    0,    0,    0,    0,    0,
      312,  313,  314,    0,    0,  315,    0,    0,    0,  316,
      311,  317,  312,  316,    0,    0,  318,  320,  321,    0,
        0,  314,    0,    0,    0,    0,  318,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  320,  324,    0,  324,
      324,  324,  324,  324,  324,  325,  325,  325,  325,  325,

      325,  325,  325,  326,    0,    0,    0,    0,  326,  327,
        0,  327,  328,    0,  328,  328,  330,  330,  331,  331,
      331,  333,    0,    0,    0,  333,  334,    0,  334,  334,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  323,  323,  323,  323,

      323,  323,  323,  323
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

#if YY_SSLScanner_DEBUG != 0
static const short int yy_rule_linenum[118] =
    {   0,
       63,   64,   65,   66,   67,   68,   69,   73,   74,   78,
       79,   83,   84,   85,   86,   88,   93,   94,   98,   99,
      100,  101,  102,  103,  104,  105,  106,  107,  112,  113,
      114,  115,  116,  117,  118,  119,  120,  121,  126,  127,
      128,  129,  130,  131,  132,  133,  137,  138,  139,  140,
      141,  142,  143,  144,  145,  146,  147,  148,  149,  150,
      151,  155,  158,  161,  164,  167,  171,  174,  177,  180,
      183,  186,  187,  188,  189,  190,  191,  192,  193,  198,
      199,  202,  203,  204,  205,  206,  207,  208,  209,  210,
      211,  212,  218,  222,  227,  228,  230,  231,  232,  236,

      241,  246,  250,  251,  255,  256,  257,  258,  259,  260,
      264,  269,  274,  286,  287,  288,  289
    } ;

#endif
static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static YY_CHAR *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#line 376 "//usr/local/lib/flexskel.cc"
#ifndef YY_USE_CLASS
static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
#else
#define yy_get_previous_state() ((yy_state_type)(yy_get_previous_state_()))
#define yy_try_NUL_trans(c) ((yy_state_type)(yy_try_NUL_trans_(c)))
#endif

#ifndef YY_USE_CLASS
#ifdef YY_SSLScanner_LEX_DEFINED
YY_SSLScanner_LEX_RETURN YY_SSLScanner_LEX ( YY_SSLScanner_LEX_PARAM )
YY_SSLScanner_LEX_PARAM_DEF
#else
YY_DECL
#endif
#else
YY_SSLScanner_LEX_RETURN YY_SSLScanner_CLASS::YY_SSLScanner_LEX ( YY_SSLScanner_LEX_PARAM)

#endif
    {
    register yy_state_type yy_current_state;
    register YY_SSLScanner_CHAR *yy_cp, *yy_bp;
    register int yy_act;

/* % user's declarations go here */ 


/* % end of prolog */ 
#line 401 "//usr/local/lib/flexskel.cc"

    if ( yy_init )
	{
	 
	 {
	 YY_USER_INIT;
	 }
	if ( ! yy_start )
	    yy_start = 1;       /* first start state */

	if ( ! yy___in )
	    yy___in = YY_SSLScanner_IFILE_DEFAULT;

	if ( ! yy___out )
	    yy___out = YY_SSLScanner_OFILE_DEFAULT;

	if ( YY_SSLScanner_CURRENT_BUFFER )
	    YY_SSLScanner_INIT_BUFFER( YY_SSLScanner_CURRENT_BUFFER, yy___in );
	else
	    YY_SSLScanner_CURRENT_BUFFER = YY_SSLScanner_CREATE_BUFFER( yy___in, YY_BUF_SIZE );

	YY_SSLScanner_LOAD_BUFFER_STATE();
	yy_init=0;
	}

    while ( 1 )         /* loops until end-of-file is reached */
	{
/* % yymore()-related code goes here */ 
#line 429 "//usr/local/lib/flexskel.cc"
	yy_cp = yy_c_buf_p;

	/* support of yy___text */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

/* % code to set up and find next match goes here */ 
	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;
yy_match:
	do
	    {
	    register YY_CHAR yy_c = yy_ec[*yy_cp];
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 324 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    *yy_state_ptr++ = yy_current_state;
	    ++yy_cp;
	    }
	while ( yy_current_state != 323 );
#line 440 "//usr/local/lib/flexskel.cc"

yy_find_action:
/* % code to find the action number goes here */ 
	yy_current_state = *--yy_state_ptr;
	yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backtracking */
	for ( ; ; ) /* until we find what rule we matched */
	    {
	    if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
		{
		yy_act = yy_acclist[yy_lp];
		if ( yy_act & YY_TRAILING_HEAD_MASK ||
		     yy_looking_for_trail_begin )
		    {
		    if ( yy_act == yy_looking_for_trail_begin )
			{
			yy_looking_for_trail_begin = 0;
			yy_act &= ~YY_TRAILING_HEAD_MASK;
			break;
			}
		    }
		else if ( yy_act & YY_TRAILING_MASK )
		    {
		    yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
		    yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
		    }
		else
		    {
		    yy_full_match = yy_cp;
		    yy_full_state = yy_state_ptr;
		    yy_full_lp = yy_lp;
		    break;
		    }
		++yy_lp;
		goto find_rule;
		}
	    --yy_cp;
	    yy_current_state = *--yy_state_ptr;
	    yy_lp = yy_accept[yy_current_state];
	    }
#line 443 "//usr/local/lib/flexskel.cc"

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:      /* this label is used only to access EOF actions */
#if YY_SSLScanner_DEBUG != 0
	if ( yy___flex_debug )
		{
		if ( yy_act == 0 )
#ifndef YY_SSLScanner_IOSTREAM
			fprintf( yy___stderr , "--scanner backtracking\n" );
#else
			yy___stderr <<"--scanner backtracking"<<endl;
#endif
		else if ( yy_act < YY_END_OF_BUFFER -1 )
#ifndef YY_SSLScanner_IOSTREAM
			fprintf( yy___stderr , 
			 "--accepting rule at line %d (\"%s\")\n",
			 yy_rule_linenum[yy_act], yy___text );
#else
			yy___stderr <<"--accepting rule at line "
                          <<(int)yy_rule_linenum[yy_act]
                          <<" (\""<<(char *)yy___text<<"\")"<<endl;
#endif
		else if ( yy_act == YY_END_OF_BUFFER -1 )
#ifndef YY_SSLScanner_IOSTREAM
			fprintf( yy___stderr , 
			 "--accepting default rule (\"%s\")\n",
			 yy___text );
#else
			yy___stderr <<"--accepting default rule"
                          <<" (\""<<(char *)yy___text<<"\")"<<endl;
#endif
		else if ( yy_act == YY_END_OF_BUFFER )
#ifndef YY_SSLScanner_IOSTREAM
			fprintf( yy___stderr , "--(end of buffer or a NUL)\n" );
#else
			yy___stderr <<"--(end of buffer or a NUL)"<<endl;
#endif
		else
#ifndef YY_SSLScanner_IOSTREAM
			fprintf( yy___stderr , "--EOF\n" );
#else
			yy___stderr <<"--EOF"<<endl;
#endif
		}
#endif
	switch ( yy_act )
	    {
/* % actions go here */ 
case 1:
#line 64 "sslscanner.l"
case 2:
#line 64 "sslscanner.l"
{ return SSLParser::TOK_INTEGER; }
	YY_BREAK
case 3:
#line 66 "sslscanner.l"
case 4:
#line 66 "sslscanner.l"
{ return SSLParser::TOK_FLOAT; }
	YY_BREAK
case 5:
#line 67 "sslscanner.l"
{ return SSLParser::OPERAND; }
	YY_BREAK
case 6:
#line 69 "sslscanner.l"
case 7:
#line 69 "sslscanner.l"
{
               yylval.str = strdup(yytext);
               return SSLParser::ENDIANNESS;
             }
	YY_BREAK
case 8:
#line 74 "sslscanner.l"
case 9:
#line 74 "sslscanner.l"
{
               yylval.str = strdup(yytext);
               return SSLParser::BIG;
             }
	YY_BREAK
case 10:
#line 79 "sslscanner.l"
case 11:
#line 79 "sslscanner.l"
{
                yylval.str = strdup(yytext);
                return SSLParser::LITTLE;
             }
	YY_BREAK
case 12:
#line 83 "sslscanner.l"
{ return SSLParser::COVERS; }
	YY_BREAK
case 13:
#line 84 "sslscanner.l"
{ return SSLParser::SHARES; }
	YY_BREAK
case 14:
#line 85 "sslscanner.l"
{ return SSLParser::FAST; }
	YY_BREAK
case 15:
#line 86 "sslscanner.l"
{ return SSLParser::FETCHEXEC; }
	YY_BREAK
case 16:
#line 88 "sslscanner.l"
{
               yylval.num = strtol(yytext+1, 0, 10);
               return SSLParser::ASSIGNSIZE;
             }
	YY_BREAK
case 17:
#line 94 "sslscanner.l"
case 18:
#line 94 "sslscanner.l"
{
               yylval.str = strdup(yytext);
               return SSLParser::LOG_OP;
             }
	YY_BREAK
case 19:
#line 99 "sslscanner.l"
case 20:
#line 100 "sslscanner.l"
case 21:
#line 101 "sslscanner.l"
case 22:
#line 102 "sslscanner.l"
case 23:
#line 103 "sslscanner.l"
case 24:
#line 104 "sslscanner.l"
case 25:
#line 105 "sslscanner.l"
case 26:
#line 106 "sslscanner.l"
case 27:
#line 107 "sslscanner.l"
case 28:
#line 107 "sslscanner.l"
{
               yylval.str = strdup(yytext);
               return SSLParser::COND_OP;
             }
	YY_BREAK
case 29:
#line 113 "sslscanner.l"
case 30:
#line 114 "sslscanner.l"
case 31:
#line 115 "sslscanner.l"
case 32:
#line 116 "sslscanner.l"
case 33:
#line 117 "sslscanner.l"
case 34:
#line 118 "sslscanner.l"
case 35:
#line 119 "sslscanner.l"
case 36:
#line 120 "sslscanner.l"
case 37:
#line 121 "sslscanner.l"
case 38:
#line 121 "sslscanner.l"
{
        yylval.str = strdup(yytext);
        return SSLParser::BIT_OP;

      }
	YY_BREAK
case 39:
#line 127 "sslscanner.l"
case 40:
#line 128 "sslscanner.l"
case 41:
#line 129 "sslscanner.l"
case 42:
#line 130 "sslscanner.l"
case 43:
#line 131 "sslscanner.l"
case 44:
#line 132 "sslscanner.l"
case 45:
#line 133 "sslscanner.l"
case 46:
#line 133 "sslscanner.l"
{
        yylval.str = strdup(yytext);
        return SSLParser::ARITH_OP;
      }
	YY_BREAK
case 47:
#line 138 "sslscanner.l"
case 48:
#line 139 "sslscanner.l"
case 49:
#line 140 "sslscanner.l"
case 50:
#line 141 "sslscanner.l"
case 51:
#line 142 "sslscanner.l"
case 52:
#line 143 "sslscanner.l"
case 53:
#line 144 "sslscanner.l"
case 54:
#line 145 "sslscanner.l"
case 55:
#line 146 "sslscanner.l"
case 56:
#line 147 "sslscanner.l"
case 57:
#line 148 "sslscanner.l"
case 58:
#line 149 "sslscanner.l"
case 59:
#line 150 "sslscanner.l"
case 60:
#line 151 "sslscanner.l"
case 61:
#line 151 "sslscanner.l"
{
        yylval.str = strdup(yytext);
        return SSLParser::FARITH_OP;
      }
	YY_BREAK
case 62:
#line 155 "sslscanner.l"
{
        return SSLParser::NOT;
      }
	YY_BREAK
case 63:
#line 158 "sslscanner.l"
{
        return SSLParser::THEN;
      }
	YY_BREAK
case 64:
#line 161 "sslscanner.l"
{
        return SSLParser::INDEX;
       }
	YY_BREAK
case 65:
#line 164 "sslscanner.l"
{
        return SSLParser::EQUATE;
      }
	YY_BREAK
case 66:
#line 167 "sslscanner.l"
{
        yylval.str = strdup(yytext);
        return SSLParser::ASSIGN;
      }
	YY_BREAK
case 67:
#line 171 "sslscanner.l"
{
        return SSLParser::TO;
      }
	YY_BREAK
case 68:
#line 174 "sslscanner.l"
{
        return SSLParser::COLON;
      }
	YY_BREAK
case 69:
#line 177 "sslscanner.l"
{
        return SSLParser::S_E;
      }
	YY_BREAK
case 70:
#line 180 "sslscanner.l"
{
        return SSLParser::AT;
      }
	YY_BREAK
case 71:
#line 183 "sslscanner.l"
{
                return SSLParser::ADDR;
            }
	YY_BREAK
case 72:
#line 187 "sslscanner.l"
case 73:
#line 188 "sslscanner.l"
case 74:
#line 189 "sslscanner.l"
case 75:
#line 190 "sslscanner.l"
case 76:
#line 191 "sslscanner.l"
case 77:
#line 192 "sslscanner.l"
case 78:
#line 193 "sslscanner.l"
case 79:
#line 193 "sslscanner.l"
{
                yylval.str = strdup(yytext);
                yylval.str[strlen(yylval.str)-1] = '\0';
                return SSLParser::CONV_FUNC;
            }
	YY_BREAK
case 80:
#line 199 "sslscanner.l"
case 81:
#line 199 "sslscanner.l"
{
                return SSLParser::FLAGMACRO;
                }
	YY_BREAK
case 82:
#line 202 "sslscanner.l"
{   return SSLParser::FPOP; }
	YY_BREAK
case 83:
#line 203 "sslscanner.l"
{   return SSLParser::FPUSH; }
	YY_BREAK
case 84:
#line 205 "sslscanner.l"
case 85:
#line 206 "sslscanner.l"
case 86:
#line 207 "sslscanner.l"
case 87:
#line 208 "sslscanner.l"
case 88:
#line 209 "sslscanner.l"
case 89:
#line 210 "sslscanner.l"
case 90:
#line 211 "sslscanner.l"
case 91:
#line 212 "sslscanner.l"
case 92:
#line 212 "sslscanner.l"
{
                yylval.str = strdup(yytext);
                yylval.str[strlen(yylval.str)-1] = '\0';
                return SSLParser::TRANSCEND;
			}
	YY_BREAK
case 93:
#line 218 "sslscanner.l"
{
				return SSLParser::SUCCESSOR;
            }
	YY_BREAK
case 94:
#line 222 "sslscanner.l"
{
                yylval.str = strdup(yytext);
                return SSLParser::TEMP;
            }
	YY_BREAK
case 95:
#line 227 "sslscanner.l"
{   return SSLParser::REG_IDX; }
	YY_BREAK
case 96:
#line 228 "sslscanner.l"
{   yylval.str = strdup(yytext);
                return SSLParser::REG_NUM; }
	YY_BREAK
case 97:
#line 230 "sslscanner.l"
{   return SSLParser::MEM_IDX; }
	YY_BREAK
case 98:
#line 231 "sslscanner.l"
{   return yytext[0];   }
	YY_BREAK
case 99:
#line 232 "sslscanner.l"
{
                yylval.str = strdup(yytext);
                return SSLParser::REG_ID;
            }
	YY_BREAK
case 100:
#line 236 "sslscanner.l"
{
                yylval.str = strdup(yytext);
                yylval.str[strlen(yylval.str)-1] = '\0';
                return SSLParser::NAME_CALL;
            }
	YY_BREAK
case 101:
#line 241 "sslscanner.l"
{
                yylval.str = strdup(yytext);
                yylval.str[strlen(yylval.str)-1] = '\0';
                return SSLParser::NAME_LOOKUP;
            }
	YY_BREAK
case 102:
#line 246 "sslscanner.l"
{
                yylval.str = strdup(yytext);
                return SSLParser::NAME;
            }
	YY_BREAK
case 103:
#line 251 "sslscanner.l"
case 104:
#line 251 "sslscanner.l"
{
                    yylval.str = strdup(yytext);
                    return SSLParser::DECOR;
            }
	YY_BREAK
case 105:
#line 255 "sslscanner.l"
{   return yytext[0];   }
	YY_BREAK
case 106:
#line 256 "sslscanner.l"
{   return yytext[0];   }
	YY_BREAK
case 107:
#line 257 "sslscanner.l"
{   return yytext[0];   }
	YY_BREAK
case 108:
#line 258 "sslscanner.l"
{   return yytext[0];   }
	YY_BREAK
case 109:
#line 259 "sslscanner.l"
{   return yytext[0];   }
	YY_BREAK
case 110:
#line 260 "sslscanner.l"
{
        yylval.dbl = atof(yytext);
        return SSLParser::FLOATNUM;
     }
	YY_BREAK
case 111:
#line 264 "sslscanner.l"
{
        yylval.num = strtol(yytext,0,10);
        return SSLParser::NUM;
     }
	YY_BREAK
case 112:
#line 269 "sslscanner.l"
{
        yylval.num = strtol(yytext,0,16);
        return SSLParser::NUM;
     }
	YY_BREAK
case 113:
#line 274 "sslscanner.l"
{
                    // a power of two
                    int sign = (yytext[0] == '-' ? -1 : 1);
                    char* start = yytext + (sign == -1 ? 4:3);

                        // David - changed to << for more efficient and 
                        // not depend on the <cmath> anymore.
                    yylval.num = 1 << (strtol(start,0,10) * sign);
                        // yylval.num = (int)pow(2,strtol(start,0,10)) * sign;
                    return SSLParser::NUM;
                }
	YY_BREAK
case 114:
#line 286 "sslscanner.l"
;
	YY_BREAK
case 115:
#line 287 "sslscanner.l"
;   /* comment */
	YY_BREAK
case 116:
#line 288 "sslscanner.l"
;
	YY_BREAK
case 117:
#line 289 "sslscanner.l"
{   // funky print-next-line-for-debug token
                    if (yyleng > MAX_LINE)
                    {
                        std::cerr << theLine + 1 << ": line too long.\n";
                        exit(1);
                    }
                    // saves the next line
                    strcpy(lineBuf, yytext+1);
                    theLine++;
                    // reparse from char 1
                    // give back all but the \n to rescan
                    yyless(1);

                    // echo the line if line tracing is turned on
                    if (traceLines)
                    std::cerr << lineBuf << std::endl;

                    // Quell a warning
                    yy_last_accepting_state = 0;
                    yy_last_accepting_cpos = 0;
                }
	YY_BREAK
case 118:
#line 310 "sslscanner.l"
ECHO;
	YY_BREAK
	    case YY_STATE_EOF(INITIAL):
		yyterminate();
#line 493 "//usr/local/lib/flexskel.cc"

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yy___text - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &YY_SSLScanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yy___text + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yy___text + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
/* % code to do backtracking for compressed tables and set up yy_cp goes here */ 
#line 541 "//usr/local/lib/flexskel.cc"
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer() )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yy___text,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yy___text + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yy___text + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yy___text + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &YY_SSLScanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yy___text + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#if YY_SSLScanner_DEBUG != 0
#ifndef YY_SSLScanner_IOSTREAM
		fprintf(yy___stderr , "action # %d\n", yy_act );
#else
		yy___stderr <<"action # "<<(int)yy_act<<endl;
#endif
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
	yyterminate();/* avoid the no return value error message on MS-C7/dos */
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */
#ifndef YY_USE_CLASS
static int yy_get_next_buffer()
#else
int YY_SSLScanner_CLASS::yy_get_next_buffer()
#endif
    {
    register YY_SSLScanner_CHAR *dest = YY_SSLScanner_CURRENT_BUFFER->yy_ch_buf;
    register YY_SSLScanner_CHAR *source = yy___text - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &YY_SSLScanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yy___text;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( YY_SSLScanner_CURRENT_BUFFER->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = YY_SSLScanner_CURRENT_BUFFER->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&YY_SSLScanner_CURRENT_BUFFER->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move - YY_MORE_ADJ == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    YY_SSLScanner_CURRENT_BUFFER->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    YY_SSLScanner_CURRENT_BUFFER->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    YY_SSLScanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    YY_SSLScanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yy___text begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yy___text = &YY_SSLScanner_CURRENT_BUFFER->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

#ifndef YY_USE_CLASS
static yy_state_type yy_get_previous_state()
#else
long YY_SSLScanner_CLASS::yy_get_previous_state_()
#endif
    {
    register yy_state_type yy_current_state;
    register YY_SSLScanner_CHAR *yy_cp;

/* % code to get the start state into yy_current_state goes here */ 
    yy_current_state = yy_start;
    yy_state_ptr = yy_state_buf;
    *yy_state_ptr++ = yy_current_state;
#line 717 "//usr/local/lib/flexskel.cc"

    for ( yy_cp = yy___text + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
/* % code to find the next state goes here */ 
	register YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 324 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	*yy_state_ptr++ = yy_current_state;
#line 721 "//usr/local/lib/flexskel.cc"
	}

#ifndef YY_USE_CLASS
    return ( yy_current_state );
#else
    return (long)( yy_current_state );
#endif
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif
#else
long YY_SSLScanner_CLASS::yy_try_NUL_trans_(long yy_current_state_)
#endif

    {
#ifndef YY_USE_CLASS
#else
    yy_state_type yy_current_state=(yy_state_type)yy_current_state_;
#endif
    register int yy_is_jam;
/* % code to find the next state, and perhaps do backtracking, goes here */ 

    register YY_CHAR yy_c = 1;
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 324 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    *yy_state_ptr++ = yy_current_state;
    yy_is_jam = (yy_current_state == 323);
#line 755 "//usr/local/lib/flexskel.cc"

#ifndef YY_USE_CLASS
    return ( yy_is_jam ? 0 : yy_current_state );
#else
    return (long)( yy_is_jam ? 0 : yy_current_state );
#endif
    }

#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
static void yyunput( YY_SSLScanner_CHAR c, register YY_SSLScanner_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_SSLScanner_CHAR c;
register YY_SSLScanner_CHAR *yy_bp;
#endif
#else
void YY_SSLScanner_CLASS::yyunput( YY_SSLScanner_CHAR c, YY_SSLScanner_CHAR *yy_bp )
#endif

    {
    register YY_SSLScanner_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yy___text */
    *yy_cp = yy_hold_char;

    if ( yy_cp < YY_SSLScanner_CURRENT_BUFFER->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register YY_SSLScanner_CHAR *dest =
	    &YY_SSLScanner_CURRENT_BUFFER->yy_ch_buf[YY_SSLScanner_CURRENT_BUFFER->yy_buf_size + 2];
	register YY_SSLScanner_CHAR *source =
	    &YY_SSLScanner_CURRENT_BUFFER->yy_ch_buf[number_to_move];

	while ( source > YY_SSLScanner_CURRENT_BUFFER->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = YY_SSLScanner_CURRENT_BUFFER->yy_buf_size;

	if ( yy_cp < YY_SSLScanner_CURRENT_BUFFER->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yy___text again */
    }

#ifndef YY_USE_CLASS
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
#else
int YY_SSLScanner_CLASS::input()
#endif
    {
    int c;
    YY_SSLScanner_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &YY_SSLScanner_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yy___text = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer() )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yy___text + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;
#ifndef YY_USE_CLASS
#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input() );
#endif
#else
		    return ( input() );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yy___text + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifndef YY_USE_CLASS
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
#else
		    YY_FATAL_ERROR( "unexpected last match in YY_SSLScanner_CLASS::input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_SSLScanner_RESTART( YY_SSLScanner_IFILE  *input_file )
#else
void YY_SSLScanner_RESTART( input_file )
YY_SSLScanner_IFILE  *input_file;
#endif
#else
void YY_SSLScanner_CLASS::YY_SSLScanner_RESTART ( YY_SSLScanner_IFILE  *input_file )
#endif

    {
    YY_SSLScanner_INIT_BUFFER( YY_SSLScanner_CURRENT_BUFFER, input_file );
    YY_SSLScanner_LOAD_BUFFER_STATE();
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_SSLScanner_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer )
#else
void YY_SSLScanner_SWITCH_TO_BUFFER( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
#else
void YY_SSLScanner_CLASS::YY_SSLScanner_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer )
#endif

    {
    if ( YY_SSLScanner_CURRENT_BUFFER == new_buffer )
	return;

    if ( YY_SSLScanner_CURRENT_BUFFER )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	YY_SSLScanner_CURRENT_BUFFER->yy_buf_pos = yy_c_buf_p;
	YY_SSLScanner_CURRENT_BUFFER->yy_n_chars = yy_n_chars;
	}

    YY_SSLScanner_CURRENT_BUFFER = new_buffer;
    YY_SSLScanner_LOAD_BUFFER_STATE();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_SSLScanner_LOAD_BUFFER_STATE( void )
#else
void YY_SSLScanner_LOAD_BUFFER_STATE()
#endif
#else
void YY_SSLScanner_CLASS::YY_SSLScanner_LOAD_BUFFER_STATE(  )
#endif

    {
    yy_n_chars = YY_SSLScanner_CURRENT_BUFFER->yy_n_chars;
    yy___text = yy_c_buf_p = YY_SSLScanner_CURRENT_BUFFER->yy_buf_pos;
    yy___in = YY_SSLScanner_CURRENT_BUFFER->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE YY_SSLScanner_CREATE_BUFFER( YY_SSLScanner_IFILE  *file, int size )
#else
YY_BUFFER_STATE YY_SSLScanner_CREATE_BUFFER( file, size )
YY_SSLScanner_IFILE  *file;
int size;
#endif
#else
YY_BUFFER_STATE YY_SSLScanner_CLASS::YY_SSLScanner_CREATE_BUFFER( YY_SSLScanner_IFILE  *file, int size )
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in YY_SSLScanner_CREATE_BUFFER()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_SSLScanner_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in YY_SSLScanner_CREATE_BUFFER()" );

    YY_SSLScanner_INIT_BUFFER( b, file );

    return ( b );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_SSLScanner_DELETE_BUFFER( YY_BUFFER_STATE b )
#else
void YY_SSLScanner_DELETE_BUFFER( b )
YY_BUFFER_STATE b;
#endif
#else
void YY_SSLScanner_CLASS::YY_SSLScanner_DELETE_BUFFER( YY_BUFFER_STATE b )
#endif

    {
    if ( b == YY_SSLScanner_CURRENT_BUFFER )
	YY_SSLScanner_CURRENT_BUFFER = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_SSLScanner_INIT_BUFFER( YY_BUFFER_STATE b, YY_SSLScanner_IFILE  *file )
#else
void YY_SSLScanner_INIT_BUFFER( b, file )
YY_BUFFER_STATE b;
YY_SSLScanner_IFILE  *file;
#endif
#else
void YY_SSLScanner_CLASS::YY_SSLScanner_INIT_BUFFER( YY_BUFFER_STATE b, YY_SSLScanner_IFILE  *file)
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }
#line 310 "sslscanner.l"

