void *__0OnwUi(int bytes);
void __0OdlPv(void *mem);
void __0oKistrstreamctPCc(void* stream, char* *str);
void *__0oHistreamrsPc(void* istream, long *l);
void __0oKistrstreamdtv();
void *__0oHistreamrsRf(void* istream, float *f);
void *__0oHistreamrsRi(void* istream, int *i);
void *__0oHistreamrsRUl(void* istream, int *ul);
void *__0oHistreamrsRl(void* istream, int *l);
void *_vector_con_(void* vect, int i1, int i2, void *func);
